apiVersion: 1

prune: true
datasources:
  - name: InfluxDB 3
    uid: octo2influx-influxdb
    type: influxdb
    access: proxy
    url: $INFLUXDB_URL
    isDefault: true
    editable: true
    jsonData:
      version: SQL
      dbName: $INFLUXDB_DATABASE
      httpMode: POST
      insecureGrpc: true
    secureJsonData:
      token: $INFLUXDB_TOKEN
